//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aca_Menu()
        {
            this.aca_Menu_x_aca_Sede = new HashSet<aca_Menu_x_aca_Sede>();
            this.aca_Menu_x_seg_usuario = new HashSet<aca_Menu_x_seg_usuario>();
        }
    
        public int IdMenu { get; set; }
        public Nullable<int> IdMenuPadre { get; set; }
        public string DescripcionMenu { get; set; }
        public int PosicionMenu { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> nivel { get; set; }
        public string web_nom_Area { get; set; }
        public string web_nom_Controller { get; set; }
        public string web_nom_Action { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aca_Menu_x_aca_Sede> aca_Menu_x_aca_Sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aca_Menu_x_seg_usuario> aca_Menu_x_seg_usuario { get; set; }
    }
}
