//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesAcademico : DbContext
    {
        public EntitiesAcademico()
            : base("name=EntitiesAcademico")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aca_AnioLectivo> aca_AnioLectivo { get; set; }
        public virtual DbSet<aca_Curso> aca_Curso { get; set; }
        public virtual DbSet<aca_Jornada> aca_Jornada { get; set; }
        public virtual DbSet<aca_Menu> aca_Menu { get; set; }
        public virtual DbSet<aca_Menu_x_aca_Sede> aca_Menu_x_aca_Sede { get; set; }
        public virtual DbSet<aca_Menu_x_seg_usuario> aca_Menu_x_seg_usuario { get; set; }
        public virtual DbSet<aca_Profesor> aca_Profesor { get; set; }
        public virtual DbSet<aca_Seccion> aca_Seccion { get; set; }
        public virtual DbSet<aca_Sede> aca_Sede { get; set; }
    }
}
