//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesSeguridadAcceso : DbContext
    {
        public EntitiesSeguridadAcceso()
            : base("name=EntitiesSeguridadAcceso")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aca_Menu> aca_Menu { get; set; }
        public virtual DbSet<aca_Menu_x_aca_Sede> aca_Menu_x_aca_Sede { get; set; }
        public virtual DbSet<aca_Menu_x_seg_usuario> aca_Menu_x_seg_usuario { get; set; }
        public virtual DbSet<seg_usuario> seg_usuario { get; set; }
        public virtual DbSet<seg_usuario_x_aca_Sede> seg_usuario_x_aca_Sede { get; set; }
        public virtual DbSet<seg_Usuario_x_Empresa> seg_Usuario_x_Empresa { get; set; }
        public virtual DbSet<vwseg_usuario_x_aca_Sede> vwseg_usuario_x_aca_Sede { get; set; }
    }
}
