//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seg_usuario()
        {
            this.aca_Menu_x_seg_usuario = new HashSet<aca_Menu_x_seg_usuario>();
            this.seg_usuario_x_aca_Sede = new HashSet<seg_usuario_x_aca_Sede>();
            this.seg_Usuario_x_Empresa = new HashSet<seg_Usuario_x_Empresa>();
        }
    
        public string IdUsuario { get; set; }
        public string Contrasena { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> Fecha_Transaccion { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotivoAnulacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> ExigirDirectivaContrasenia { get; set; }
        public Nullable<bool> CambiarContraseniaSgtSesion { get; set; }
        public bool es_super_admin { get; set; }
        public string contrasena_admin { get; set; }
        public Nullable<bool> EsContador { get; set; }
        public Nullable<int> IdMenu { get; set; }
        public string IPUsuario { get; set; }
        public string IPImpresora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aca_Menu_x_seg_usuario> aca_Menu_x_seg_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seg_usuario_x_aca_Sede> seg_usuario_x_aca_Sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seg_Usuario_x_Empresa> seg_Usuario_x_Empresa { get; set; }
    }
}
